language: python

python: "3.5"

env:
  global:
    - DJANGO_SETTINGS_MODULE=bord.settings
    - DATABASE_URL=postgres://postgres@localhost/travis_ci_test
    - SECRET_KEY=x

services: postgresql

addons:
  postgresql: "9.1"

before_script: psql -c 'create database travis_ci_test;' -U postgres

install: pip install -r requirements.txt

script: py.test --cov

after_success: coveralls
